GET http://localhost:9000/api/produits
Content-Type: application/json

###
POST http://localhost:9000/api/produits
Content-Type: application/json

{
    "nom": "Feuille de magnoc",
    "prix": 20.00,
    "description" : "Aliment riche en fibres et en vitamines, idéale pour les plats d'hiver.",
    "quantite": 5,
    "categorie": {
        "id": 2
    }
}


###
GET http://localhost:9000/api/produits/2
Content-Type: application/json

###
DELETE http://localhost:9000/api/produits/1
Content-Type: application/json





###
GET http://localhost:9000/api/categories
Content-Type: application/json

###
POST http://localhost:9000/api/categories
Content-Type: application/json

{
    "nom": "Alimentaire"
}

###
GET http://localhost:9000/api/produits/categorie/2
Content-Type: application/json
